name: Bazel Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: public-amd64-small

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bazel
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - name: run tests
        run: |
          cd bazel/gtest
          bazel test //:hello_test


