name: Bazel Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: public-amd64-small

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
        working-directory: bazel/gtest
      - run: |
          echo "here"
          pwd
          bazel test


