name: PR Factory

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  createPR:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated PR
          title: Automated PR
          body: This is an automated pull request.
          branch: automated-pr
