name: PR Factory

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated PR"
          title: "Automated PR"
          body: "This is an automated pull request."
          branch: "automated-pr"
