name: GoLang Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: public-amd64-small

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go Action
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          go install gotest.tools/gotestsum@latest

      - name: Run gotestsum tests
        uses: trunk-io/analytics-uploader@main
        with:
          # Path to your test results.
          junit-paths: "**/*_test.xml"
          # Provide your Trunk organization slug.
          org-slug: trunk-staging-org
          # Provide your Trunk API token as a GitHub secret.
          token: ${{ secrets.TRUNK_STAGING_ORG_API_TOKEN }}
          working-directory: go/src
          run: gotestsum --junitfile gotestsum_test.xml
        env:
          TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io

      - name: Run go-junit-report tests
        uses: trunk-io/analytics-uploader@main
        with:
          # Path to your test results.
          junit-paths: "**/*_test.xml"
          # Provide your Trunk organization slug.
          org-slug: trunk-staging-org
          # Provide your Trunk API token as a GitHub secret.
          token: ${{ secrets.TRUNK_STAGING_ORG_API_TOKEN }}
          run: go test -v 2>&1 ./... | go-junit-report -set-exit-code > report_test.xml
        env:
          TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io


