name: Run Mocha Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Trunk install
        uses: trunk-io/trunk-action/setup@v1

      - name: Install Dependencies
        run: |
          trunk install
          pnpm install

      - name: Run Tests
        run: npm test
