name: Run Mocha Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: [self-hosted, macOS]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      #   - name: Trunk install
      #     uses: trunk-io/trunk-action/setup@latest

        - name: Install Dependencies
          run: |l
            pnpm install

      - name: Run Tests
        run: npm test
