name: Run Behave Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run behave tests
        run: behave --junit-directory=python/results --junit python/behave

      - name: Flaky Test Reporter
        if: ${{ always() }}
        uses: trunk-io/analytics-uploader@main
        with:
          # Path to your test results.
          junit-paths: "**/python/results/*-behave.xml"
          # Provide your Trunk organization slug.
          org-slug: trunk-staging-org
          # Provide your Trunk API token as a GitHub secret.
          token: ${{ secrets.TRUNK_STAGING_ORG_API_TOKEN }}
        env:
          TRUNK_API_ADDRESS: https://api.trunk-staging.io/v1/metrics/createBundleUpload
        continue-on-error: true

  retry-failed-test:
    runs-on: [self-hosted, linux]
    needs: [test]
    if: failure()
    steps:
      - uses: actions/checkout@v4

      - name: wait
        run: sleep 30

      - name: Rerun failed jobs in the current workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh run rerun ${{ github.run_id }}
